### PR TITLE
Quick: Support Non-Bootstrap Link & Picture Plugins

### PR DESCRIPTION
**Pull request by tacc-wbomar**
# Overview

Restore support for Generic plugins that `djangocms_bootstrap4` removes.

<details><summary>Why?</summary>

Most of the time, the extra features of Bootstrap4's link and image are:
1. unused by users
2. undesired by designers
3. add unnecessary complexity to development of TACC plugins that need simple image and link feature

</details>

# Changes

- Register new TACC plugin to re-register `LinkPlugin` (if Bootstrap's respective plugin is present).
- Register new TACC plugin to re-register `PicturePluign` (if Bootstrap's respective version is present).

# Screenshots

__Note__: I propose we mark the relevant Bootstrap plugins as deprecated.

<details>

Though Bootstrap plugins are still available (to support existing usage), they will __not__ be allowed to be nested within TACC plugins. Also, TACC plugins will extend Generic plugins, not Bootstrap plugins.

</details>
<details><summary>Legend</summary>

- Blue plugins are for links.
- Yellow plugins are for images.
- Outlined Bootstrap plugins are undesirable.
- Outlined Generic plugins are undesirable.

</details>

| Description | Image 1 | Image 2 |
| --- | --- | --- |
| | Link | Image |
| Add Plugins | Link Add | Image Add |
| Generic Plugin Form | Generic Link Form | Generic Image Form |
| Bootstrap Plugin Form | Bootstrap Link Form | Bootstrap Image Form |
| | Not Within "Text" Plugin | Within "Text" Plugin |
| Render Plugins | Bootstrap   Generic - Render - Not Within Text | Bootstrap   Generic - Render - Within Text |
| Plugin Structure | Bootstrap   Generic - Structure - Not Within Text | Bootstrap   Generic - Structure - Within Text |

# Testing

You may test locally or on servers that have deployed this code.

> __Last Recorded Deploys__
> - [Frontera (dev)](https://dev.fronteraweb.tacc.utexas.edu/) was [Build #454 (Aug 9, 2021 1:02:37 PM)](https://jenkins01.tacc.utexas.edu/job/Core_Portal_Deploy/454/) via `site/main/frontera` (which has this branch and more)
> - [Core (dev)](https://dev.cep.tacc.utexas.edu/) was [Build #453 (Aug 9, 2021 1:04:25 PM)](https://jenkins01.tacc.utexas.edu/job/Core_Portal_Deploy/453/) via `site/main/frontera` (which has this branch and more)

1. Ensure that both "Generic" plugins, "Link" and "Image", are:
	- available to add
	- functional
	- __not__ tagged as needing attention
	- __not__ described as deprecated
2. Ensure that both "Bootstrap4" plugins, "Link / Button" and "Picture / Image", are:
	- available to add
	- functional
	- tagged as needing attention
	- described as deprecated

# Notes

## Known Issues

1. <details>
	<summary>Should We Prevent New Instances of Bootstrap Plugins, but Support Existing Ones?</summary>

	__Maybe.__ It depends on whether there are valid use cases for the plugins extra features that TACC cannot or will not provide.

	</details>

2. <details>
	<summary>How Would We Prevent New Instances of Bootstrap Plugins, but Support Existing Ones?</summary>

	Tasks:
	- Hide plugins from plugin add list from non-admin users (so admins retain full control).
	- But show plugins in structure list (so they can be edited if already in use).

	Ideas:
	- CSS:
    	```css
    	/* HELP: How to limit this to non-admin users? */
    	div.cms .cms-plugin-picker .cms-submenu-item a[data-rel="add"][href="TaccsiteNewsArticleListPlugin"] {
        	display: none;
    	}
    ```

	</details>

### CODE REVIEW

**Comment by taoteg** [comment]
While testing:

2. Ensure that both plugins, "Generic" ▸ "Link" and "Bootstrap4" ▸ "Link / Button", are available and functional.

I ran into this error for the "Link/Button" plugin.

Screen Shot 2021-08-19 at 4 50 17 PM

It seems to be the only one failing, but there is no logging I can find.
The container passes the `manage.py cms check`.
Not sure what is exploding here...

**Comment by taoteg** [comment]
But to be clear, all items were present in the list and worked fine with the above caveat of the Bootstrap4 Link/Button:

Screen Shot 2021-08-19 at 5 02 46 PM

**Comment by taoteg** [comment]
Oddly, this does show up in the container log for the cms:

Screen Shot 2021-08-19 at 5 11 08 PM

**Comment by tacc-wbomar** [comment]
@taoteg Regarding ["Please correct the error below", but no error below](https://github.com/TACC/Core-CMS/pull/278/#issuecomment-902278113), the error is possibly hidden within the "Link settings". I will try to reproduce.

<details>
<summary>Thoughts about Possibly Hidden Error</summary>

- If hidden, I will check whether Django CMS is not opening or consider showing "Link settings" by default.
- If **not** hidden, then I have created a bug and will exterminate it.

</details>

**Comment by tacc-wbomar** [comment]
@taoteg Regarding [`Bootstrap4PicturePlugin` showing up in logs](https://github.com/TACC/Core-CMS/pull/278/#issuecomment-902285160), if that comes up when saving a plugin that is **not** `Bootstrap4PicturePlugin`, then that is odd. I'll watch logs. Thanks.

**Comment by tacc-wbomar** [comment]
@taoteg I have fixed the issues. Please, review again.

**Review by taoteg — APPROVED** [review]
All working as advertised.
I like the "labeling as deprecated" approach.

Suggestion: Eventually we inventory our portals/sites and ensure none are using the deprecated plugins then remove then forever.

**Comment by tacc-wbomar** [comment]
Thank you. Regarding,

> Suggestion: Eventually we inventory our portals/sites and ensure none are using the deprecated plugins then remove then forever.
> – @taoteg

Well, most sites do. The `Bootstrap4Picture` is used on any site with pictures; Texascale has many.

_At least the `Bootstrap4Link` has probably __never__ been used. Links I've seen are all via Text plugin hyperlink._

**Pull request merged**
