### PR TITLE
CMD-112 Let Client CMS Overwrite Core-CMS Confirmation Email

### PR DESCRIPTION
**Pull request by R-Tomas-Gonzalez**
## Overview

Set up a text file and a html file in an assets folder. First step to allowing them to be overwritten by Client CMS.

## Related

- [CMD-112](https://tacc-main.atlassian.net/browse/CMD-112)
- required by https://github.com/TACC/tup-ui/pull/448
- expands upon #817

## Changes

Add an assets folder
Add a text and html file
Modify the {site_name} portion of the files and return that

## Testing
1. Add a new form with an email field
2. Open Docker image
3. Check that log contains two emails when provided in the form

## UI

| Email |
| --- |
| Screenshot 2024-03-26 at 6 28 31 PM |

### CODE REVIEW

**Review by wesleyboar — COMMENTED** [review]
Looks great. I tried to test via https://github.com/TACC/tup-ui/pull/448. Test failed. I am not sure whether there's more to do in Core-CMS or in TUP-UI.

**Comment by wesleyboar** [comment]
> [!IMPORTANT]
> **Paused.** Pending change in CMD-112 requirements to [use custom setting, not files](https://tacc-main.atlassian.net/browse/CMD-112?focusedCommentId=19738).

**Comment by R-Tomas-Gonzalez** [comment]
Meant to detail [8cd3b46](https://github.com/TACC/Core-CMS/pull/826/commits/8cd3b46ea51bd641c9218f09fbb82564e5f802b7) with "cleanup path to assets in apps.py"

**Review by wesleyboar — APPROVED** [review]
**Test Successful**

<details><summary>Core-CMS Log</summary>

```log
core_cms                | [DJANGO] DEBUG 2024-04-01 15:30:35,810 UTC apps portal.common_apps.email_management.apps.callback:40: received submission from Help
core_cms                | Content-Type: multipart/alternative;
core_cms                |  boundary="===============9166022759637109126=="
core_cms                | MIME-Version: 1.0
core_cms                | Subject: Form Submission - Help
core_cms                | From: webmaster@localhost
core_cms                | To: wbomar@tacc.utexas.edu
core_cms                | Date: Mon, 01 Apr 2024 20:30:35 -0000
core_cms                | Message-ID: <171200343581.8.1657091193992236690@core_cms>
core_cms                | 
core_cms                | --===============9166022759637109126==
core_cms                | Content-Type: text/plain; charset="utf-8"
core_cms                | MIME-Version: 1.0
core_cms                | Content-Transfer-Encoding: 7bit
core_cms                | 
core_cms                | 
core_cms                | 
core_cms                | Form: Help
core_cms                | Date: 1st April 2024 15:30
core_cms                | 
core_cms                | 
core_cms                | Email:
core_cms                | test@go.here
core_cms                | 
core_cms                | 
core_cms                | Sent via http://localhost:8000
core_cms                | 
core_cms                | --===============9166022759637109126==
core_cms                | Content-Type: text/html; charset="utf-8"
core_cms                | MIME-Version: 1.0
core_cms                | Content-Transfer-Encoding: 7bit
core_cms                | 
core_cms                | <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
core_cms                | <html xmlns="http://www.w3.org/1999/xhtml">
core_cms                |     <head>
core_cms                |         <meta name="viewport" content="width=device-width" />
core_cms                |         <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
core_cms                |         <title>Form Submission - Help</title>
core_cms                |     </head>
core_cms                |     <body itemscope itemtype="http://schema.org/EmailMessage">
core_cms                |         <h1>Help</h1>
core_cms                |         <p><strong>Date:</strong> 1st April 2024 15:30</p>
core_cms                |         
core_cms                |             <p>
core_cms                |                 <strong>Email:</strong><br/>
core_cms                |                 test@go.here
core_cms                |             </p>
core_cms                |         
core_cms                |         Sent via <a href="http://localhost:8000/help/">localhost:8000/help/</a>
core_cms                |     </body>
core_cms                | </html>
core_cms                | 
core_cms                | --===============9166022759637109126==--
core_cms                | 
core_cms                | -------------------------------------------------------------------------------
core_cms                | [DJANGO] DEBUG 2024-04-01 15:30:35,810 UTC apps portal.common_apps.email_management.apps.callback:41: <class 'dict'>
core_cms                | Content-Type: multipart/alternative;
core_cms                |  boundary="===============6996074916908672420=="
core_cms                | MIME-Version: 1.0
core_cms                | Subject: TACC Form Submission Received: Help
core_cms                | From: no-reply@tacc.utexas.edu
core_cms                | To: test@go.here
core_cms                | Date: Mon, 01 Apr 2024 20:30:35 -0000
core_cms                | Message-ID: <171200343581.8.1126815754576860993@core_cms>
core_cms                | 
core_cms                | --===============6996074916908672420==
core_cms                | Content-Type: text/plain; charset="utf-8"
core_cms                | MIME-Version: 1.0
core_cms                | Content-Transfer-Encoding: 7bit
core_cms                | 
core_cms                | 
core_cms                | Greetings,
core_cms                | 
core_cms                | You have successfully submitted a form on the example.com website. Thank you for your submission.
core_cms                | 
core_cms                | Sincerely,
core_cms                | example.com Communications
core_cms                | 
core_cms                | --===============6996074916908672420==
core_cms                | Content-Type: text/html; charset="utf-8"
core_cms                | MIME-Version: 1.0
core_cms                | Content-Transfer-Encoding: 7bit
core_cms                | 
core_cms                | 
core_cms                | <p>Greetings,</p>
core_cms                | <p>
core_cms                |   You have successfully submitted a form on the example.com website. Thank you
core_cms                |   for your submission.
core_cms                | </p>
core_cms                | <p>
core_cms                |   Sincerely,<br />
core_cms                |   example.com Communications
core_cms                | </p>
core_cms                | 
core_cms                | --===============6996074916908672420==--
core_cms                | 
core_cms                | -------------------------------------------------------------------------------
```

</details>

TUP-UI PR:
- https://github.com/TACC/tup-ui/pull/448

**Pull request merged**
