### PR TITLE
GH-93, GH-142, GH-133: Article List Plugins & Styles

### PR DESCRIPTION
**Pull request by tacc-wbomar**
## Important

Merged for posterity. This version is newer than:
- https://github.com/TACC/Core-CMS/pull/264

## To Do

<details><summary>Done</summary>

1. [x] Resolve merge conflicts with `main`.
1. [x] Redeploy (with latest `main` merged in).
1. [x] [FP-1252: Clone Frontera CMS Prod to Pre-Prod](https://jira.tacc.utexas.edu/browse/FP-1252)
1. [x] Perform testing steps on pre-prod.
1. ~~If all goes well, merge.~~\*
1. [x] As part of or follow-up to [FP-1231](https://jira.tacc.utexas.edu/browse/FP-1231), review:
	- https://github.com/tacc-wbomar/Core-CMS-Plugin-Static-Article-List
	- https://github.com/tacc-wbomar/Core-CMS-Plugin-Static-Article-Preview

</details>

<details open><summary>Pending</summary>

- [ ] [Create ticket to] not use plugins\* *but* retain otherwise desirable changes.

> \* Belated evaluation decrees static article plugins are not necessary.

</details>

## Requires

- https://github.com/TACC/Core-CMS-Resources/pull/62
  (for styles specific to Frontera homepage)

## Overview

Implement all plugins and styles required for Article Lists on [new Frontera homepage](https://frontera-portal.tacc.utexas.edu/home-2021-03/).

## Issues

- #93
- #142
- #133
&nbsp;+
- https://github.com/TACC/Core-CMS/issues/291
- #112

### Plugins

- Add article plugins.
- Add plugin helper functions.
- <details><summary>complete changelog</summary>

	- __Doc__: Add plugin documentation.
	- __Doc__: Describe intent and architecture of static article plugins.
	-  _Doc_:  Fix typos and add missing comments.
	- __New__: Add many plugin helper methods.
	-  _Fix_:  Blockquote CMS Plugin: Fix small mistakes.
	- __New__: Blockquote & Offset CMS Plugin: couple direction choices with classnames.\*
	-  _Fix_:  Sample Plugin: small mistakes.
	- __New__: Article List (Static) Plugin.
	- __New__: Article Preview (Static) Plugin.

	<br />

	> \* The choice values and descriptions and resulting classnames are in a dictionary (just like the Article plugins).

	</details>

## Styles

- Add new stylesheets for article components.
- Update stylesheets for article-scoped styles.
- Cleanup article mixins.
- Tweak homepage-specific/relevant styles.
- <details><summary>(complete changelog)</summary>

	- __New__: Article List Component `.c-article-list`.
	- __New__: Article Preview Component `.c-article-preview`.
	- __New__: Date Component.
	- _Minor_: Tweak HTML Elements `dt`.
	- __New__: Replace class mixin `.x-article-...` with invisible mixin `%x-article-...`.
	- __New__: Remove mixin `x-article-...--gapless`.
	- _Minor_: Deprecate previous Article List Scope `.s-article-list`.
	- _Minor_: Deprecate previous Article Preview Scope `.s-article-preview`.
	- __New__: Article List Scope `.s-article-preview`.
	- _Minor_: Tweak Home Scope `.s-home(...)` selectors—for article styling—to use classnames not tags.

	</details>

## Screenshots

__Ignore__ header, banner, intro text, and system monitor.

__Deployed__ at [Frontera (dev) homepage](https://dev.fronteraweb.tacc.utexas.edu/).

<details>
<summary><em><strong>Dev</strong> Server</em> Screenshots Taken on After Original Review</summary>

| 576px | 768px | 992px | 1200px | 1400px | 1680px |
| --- | --- | --- | --- | --- | --- |
| FP-93 - 576 | FP-93 - 768 | FP-93 - 992 | FP-93 - 1200 | FP-93 - 1400 | FP-93 - 1680 |

</details>

<details>
<summary><em><strong>Local</strong> Server</em> Screenshots Used for Original Review</summary>

| 576px | 768px | 992px | 1200px | 1400px | 1680px |
| --- | --- | --- | --- | --- | --- |
| FP-93 - 576 | FP-93 - 768 | FP-93 - 992 | FP-93 - 1200 | FP-93 - 1400 | FP-93 - 1680 |

</details>

## Testing

> __Last Recorded Deploys__
> - [Frontera (dev)](https://dev.fronteraweb.tacc.utexas.edu/) was [Build #454 (Aug 9, 2021 1:02:37 PM)](https://jenkins01.tacc.utexas.edu/job/Core_Portal_Deploy/454/) via `site/main/frontera` (has this branch and more)
> - [Core (dev)](https://dev.cep.tacc.utexas.edu/) was [Build #453 (Aug 9, 2021 1:04:25 PM)](https://jenkins01.tacc.utexas.edu/job/Core_Portal_Deploy/453/) via `site/main/frontera` (has this branch and more)

<details>
<summary>☑️&nbsp; <s>Convert Frontera Dev Homepage to Use New Article Plugins</s></summary>

---

__Notice__: @tacc-wbomar already did this.

---

1. Recreate bottom half of homepage (beneath System Monitor) using these new plugins:
    - News Article List (Static)
        - News Article Preview (Static)
    - Allocations Article List (Static)
        - Allocations Article Preview (Static)
    - Document Article List (Static)
        - Document Article Preview (Static)
    - Event Article List (Static)
        - Event Article Preview (Static)
2. Skip/Remove the following classes from the Container around News article list section:
    - `s-article-list--layout-d`
    - `s-article-list--layout-compact`
    - `s-article-list--news`
3. Skip/Remove all classes from the other article list section.

</details>

<details>
<summary>➡️&nbsp; Duplicate Frontera Dev Homepage and Play Around with its New Plugins</summary>

<br />

1. Clone the [Frontera (dev) homepage](https://dev.fronteraweb.tacc.utexas.edu/).
2. Poke around at __the plugins below the System Monitor__.
3. Report any oddities or failures.

</details>

<details>
<summary>➡️&nbsp; Compare Homepage with Plugins to Prod Homepage</summary>

<br />

1. Result looks* like [Frontera (prod) Homepage](https://frontera-portal.tacc.utexas.edu), except:
    - Docs article preview title and line height matches those of Events.
    - Articles may be different (because @tacc-wbomar did not update images & text).
    - The "See ..." links beneath each set of articles has a new encircled-arrow icon.
2. Result behaves* like [Frontera (prod) Homepage](https://frontera-portal.tacc.utexas.edu), except:
    - Allocations has more vertical space available from 992px to 1680px.†

> \* Where "looks like" is static UI, and "behaves like" is responsive UI (UI adapts to window size change).
>
> † Because Docs article preview styling uses more vertical space because styles we updated to match Events.

</details>

## Notes

1. <details>
	<summary>Independent Repos for Plugins</summary>

	This has been tested using the following independent plugins via `task/FP-1231-extract-plugins` (reverted) commit 2c19af7:
	- https://github.com/tacc-wbomar/Core-CMS-Plugin-Static-Article-Preview
	- https://github.com/tacc-wbomar/Core-CMS-Plugin-Static-Article-List

	</details>

### CODE REVIEW

**Comment by tacc-wbomar** [comment]
@taoteg I [added a commit](https://github.com/TACC/Core-CMS/pull/280#commits-pushed-eea0768) relevant to testing this PR. Please pull. Sorry for the unexpected change.

<details>
<summary>Why the Change?</summary>

1. eea0768 Merge from `main` to resolve any possible conflicts _before_ merging to `main`.
2. __1729430 When I Frankenstein-ed this PR out of a larger PR, I neglected the complete content of `helpers.py`.__

</details>

**Comment by tacc-wbomar** [comment]
@taoteg The recent updates are hotfixes (for #312) and v1 migration styles in submod. They are not major changes to the diff.

**Comment by tacc-wbomar** [comment]
@taoteg Recent commit c4186df removes errant, unrelated Core-CMS-Resources changes. It does not affect your testing.

**Review by taoteg — APPROVED** [review]
Everything works as advertised for me, no errors and all tests passing that I expected too. I tested the layout by recreating the frontera dev site (as best I could) locally.

In the future, perhaps we can find a way to define test content that lives outside another CMS for testing? Perhaps as a fixture (not sure how that would work for CMS content) or as a documented 'lorem ipsum-esque' design that can be manually created in the cms structure view without needing specific assets or admin in a host system?

**Comment by tacc-wbomar** [comment]
> In the future, perhaps we can find a way to define test content that lives outside another CMS for testing? Perhaps as a fixture (not sure how that would work for CMS content) or as a documented 'lorem ipsum-esque' design that can be manually created in the cms structure view without needing specific assets or admin in a host system?

@taoteg Yes, please. I am hoping an automated [CMS pattern library](https://github.com/TACC/Core-CMS/discussions/155) would provide isolated test cases for plugins (this PR added many). I don't know how to that yet, either.

**Comment by tacc-wbomar** [comment]
Merged—**not** to `main`—for posterity.

**Comment by tacc-wbomar** [comment]
The plugin instances used on `frontera-home-2021-03` (which had existed at https://dev.fronteraweb.tacc.utexas.edu/ before [FP-1360](https://jira.tacc.utexas.edu/browse/FP-1360)) are preserved in case needed for testing changes pulled from this PR:
[plugins-frontera-home-2021-03-with-plugins--mod-for-import.zip](https://github.com/TACC/Core-CMS/files/7542103/plugins-frontera-home-2021-03-with-plugins--mod-for-import.zip)

**Pull request merged**
