### PR TITLE
feat(ecep): add google analytics javascript

### PR DESCRIPTION
**Pull request by wesleyboar**
## Overview

Point to ECEP-specific Google Analytics code.

## Related

- [ECEPWEB-206](https://jira.tacc.utexas.edu/browse/ECEPWEB-206)
- requires https://github.com/TACC/Core-CMS-Resources/pull/156

## Changes

- update submodule i.e. `taccsite_custom`

## Testing

1. Confirm Google Analytics loads on several pages at https://prod.ecep.tacc.utexas.edu/.
    - http://www.gachecker.com/ (website, online checker)
    - https://get.google.com/tagassistant/ (browser extension)

## UI & Notes

The Google Universal Analytics is not working on their current site. The same error occurs when implementing on the new site. A notice also appears (that the code should be in the head); I know this, and can do so much easier after [FP-1652](https://jira.tacc.utexas.edu/browse/FP-1652) (and have noted such in the template and snippet instance).

| | prod | pprd | old |
| - | - | - | - |
| analytics check | ecep prod analytics check | ecep pprd analytics check | ecep old analytics check |
| tag check | ecep prod tag check | ecep pprd tag check | ecep old tag check |

### CODE REVIEW

**Comment by taoteg** [comment]
I know this is urgent AND languishing. What would you like to do to proceed here? 

I am amenable to the solutions you identified if you think they are the correct path. 

Otherwise I do not see how we can dynamically support the range of GA codes our portal use without a flexible analytics snippet solution that inserts the code into the template head (because the gtag code differs depending on which type of code the portal uses - there are options besides the Universal option).

**Review by taoteg — APPROVED** [review]
Just approved the Resources related PR as well.

**Comment by wesleyboar** [comment]
I dislike this solution. One of my tasks this week is to review [your commit to give ECEP Analytics](https://github.com/TACC/Core-Portal-Deployments/commit/8c203d5) and hopefully kill this solution. I did this only to say I ported the Google Analytics code as is and wash my hands, without testing whether our code would work for ECEP. Now I have the bandwidth to test.

<details><summary>Steps I Will Do</summary>

1. Review [your commit for Google Analytics](https://github.com/TACC/Core-Portal-Deployments/commit/8c203d5).
2. Test Google Tags on [ecepalliance.org](http://ecepalliance.org/) (via browser plugin).
3. Abandon my solution if it is ineffectual or redundant.
4. Confirm any other change with John G.

</details>

**Comment by wesleyboar** [comment]
I've converted to draft so I do not accidentally merge.

**Comment by wesleyboar** [comment]
Closed. See [ECEPWEB-223 comment](https://jira.tacc.utexas.edu/browse/ECEPWEB-223?focusedId=26111&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-26111).

**Pull request closed without merging**
