### PR TITLE
feat(server): fp-1952 tighter ES network settings

### PR DESCRIPTION
**Pull request by wesleyboar**
## Overview

Set up Elasticsearch network to limit exposure of the software on the network.

## Related

- [FP-1952](https://jira.tacc.utexas.edu/browse/FP-1952)
- mimics https://github.com/TACC/Core-Portal/pull/752

## Changes

- limit network to only localhost

## Testing

1. Run development environment using these new settings.
2. Test that Elasticsearch still works:
    1. Add a CMS page **and** confirm re-index occurs and is accurate.[^1]
    2. Publish a CMS page **and** confirm re-index occurs and is accurate.[^1]
    4. Delete a CMS page **and** confirm re-index occurs and is accurate.[^1]
    5. Add text to a CMS page and verify page appears in a search.

[^1]: You can check container logs for a message saying that re-index has occurred. You can check http://localhost:9201/cms-dev-cms/_search to confirm search index has expected page content.

## UI

Skipped.

## Notes

<details><summary>Archived</summary>

Elasticsearch [**Networking** reference](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html#modules-network) suggests [**`network.host`**](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html#common-network-settings) should be [`_local_`](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html#network-interface-values) instead of `0.0.0.0`.

**Update**: But doing so would interfere with Docker cross-container communication.
</details>

### CODE REVIEW

**Comment by wesleyboar** [comment]
The summary is updated to reflect state of code after new commits.

**Review by wesleyboar — COMMENTED** [review]
Basic functionality is unchanged.

http://localhost:9201/cms-dev-cms/_search returns accurate index.

**Review by wesleyboar — COMMENTED** [review]
With ngrok active, the search is **still**[^1] inaccessible from external network.

E.g. http://5ee5-...-7c6e.ngrok.io:9201 is not found.

[^1]: This was also the case for `main` branch.

**Review by jarosenb — APPROVED** [review]

**Comment by wesleyboar** [comment]
I would approve, but I created the PR. The approval from Jake is a stand-in for my own approval of his change.

**Pull request merged**
