### PR TITLE
GH-73: Blockquote, Offset & Sample Plugins

### PR DESCRIPTION
**Pull request by tacc-wbomar**
# To Do

- [ ] [How to require fields if checkbox is checked?](https://github.com/TACC/Core-CMS/pull/275#issuecomment-919578223)

# Dependencies

- This PR depends on PR https://github.com/TACC/Core-CMS-Resources/pull/61 for Texascale-specific styles.

# Overview

- Create TACC "Blockquote" plugin.
- Create basic TACC "Offset Content" plugin.

# Issues

- #73
- #66
    &nbsp;+
- #265
- https://github.com/TACC/Core-CMS-Resources/pull/95

# Changes

- Create Offset plugin and styles.
- Create Blockquote plugin and styles.
- Add `2400px` breakpoint `--max-wide-…`.
- Tweak Sample plugin based on lessons learned.
- Clean up Texascale project-specific styles.
- <details><summary>(complete changelog)</summary>

	## Major

	- __New__: Create `o-offset-content` component, which:
    	- offsets its content to the left or right of parent content
	- __New__: Create `c-blockquote` component, which:
    	- marks up and styles content as a quote.
    	- supports a set of options for adding a citation.
	- __New__: Create `o-offset-content` component, which:
    	- offsets its content to the left or right of parent content
	- __New__: Create "Offset …" plugin, which:
    	- uses `o-offset-content` styles.
    	- exists to have another plugin inside it.

	## Minor

	- __New__: Install "Blockquote" and "Offset …" plugins.
	- _Minor_: Add `2400px` to `@custom-media` as `--max-wide-…`.
	- _Minor_: Update "Sample" plugin
		- remove unused dependency
    	- organizational comments
   		- rename `utils.py` to `helpers.py`
    	- remove what would become redundant documentation
    	- use internationalization formatting for user-facing strings with variables
    	- improve & add docblocks

	## Submodule

	- https://github.com/TACC/Core-CMS-Resources/pull/61

	</details>

# Screenshots & Testing

<details><summary>Remote Server</summary>

1. [Login to Texascale Dev](https://texascale-dev.tacc.utexas.edu/admin).
2. (Optionally) [Login to Texascale Prod](https://texascale.org/admin).
3. Compare rendered results of these pages' plugins to show the same content:
	- [Texascale Dev "Urgent Computing" article](https://texascale-dev.tacc.utexas.edu/2020/feature-stories/urgent-computing/)
		- (TACC) Offset Content → (Bootstrap) Figure (__no__ "Advanced settings", `class` attribute)
		- (TACC) Offset Content → (TACC) Blockquote

	- [Texascale Prod "Urgent Computing" article](https://texascale.org/2020/feature-stories/urgent-computing/)
		- (Bootstrap) Figure (with "Advanced settings", `class` attribute)
		- (Bootstrap) Blockquote (with "Advanced settings", `class` attribute)

</details>

<details><summary>(Optional, but Thorough) Local Server</summary>

## All Steps

First, `docker exec -it core_cms /bin/bash`. Then:

    python3 manage.py migrate
    npm ci
    npm run build
    python3 manage.py collectstatic --no-input

Next, test plugins:

1. TACC Plugins has new plugins…

    <details>
    <summary>Plugins</summary>

   - "Blockquote"
   - "Offset Content"

    </details>
    <details>
    <summary>Screenshot</summary>

    New Plugins - Blockquote, Offset Content (List)

    </details>

1. Blockquote has options…

    <details><summary>Options</summary>

    - (required) Quote
    - (optional) Origin
    - (optional) Citation
    - (configurable) Citation
        - author/speaker
        - source text
        - source URL
    - (optional, collapsed) Layout: Offset
    - (optional, collapsed) Advanced Settings: Attributes

    </details>
    <details><summary>Screenshot</summary>

    New Plugins - Blockquote (Options)

    </details>

1. New plugins render…

    <details><summary>Features</summary>

    - correct layout (alignment depends on options)
    - Core (basic) style
    - Texascale (per-project) style (matches [existing Texascale article](https://texascale.org/2020/feature-stories/urgent-computing/))

    </details>
    <details><summary>Screenshot</summary>

    New Plugins - Blockquote, Offset Content (On Page)

    </details>

1. Blockquote has options…

    <details><summary>Options</summary>

    - (required) Direction
    - (optional, collapsed) Advanced Settings: Attributes

    </details>
    <details><summary>Screenshot</summary>

    New Plugins - Offset Content (Options)

    </details>

1. Blockquote can be offset via "Layout" options __which are__ Offset Content's "Direction" options…

    <details><summary>Values</summary>

    - Left
    - Right

    </details>
    <details><summary>Screenshot</summary>

    New Plugins - Offset Content via Blockquote

    </details>

</details>

# Notes

<details><summary>Archived</summary>

1. <details><summary>⚠️&nbsp; Unable to Publish on Texascale Dev Server</summary>

	502 Error on publish. Re-index fails.

	Logs:
	```
	Sep 01 17:36:55 texascale gunicorn[114099]: Removing all documents from your index because you said so.
	Sep 01 17:36:55 texascale gunicorn[114099]: All documents removed.
	Sep 01 17:36:55 texascale gunicorn[114099]: Indexing 87 titles
	Sep 01 17:36:55 texascale gunicorn[114099]: [2021-09-01 17:36:55 -0500] [114153] [INFO] Booting worker with pid: 114153
	Sep 01 18:06:53 texascale gunicorn[114099]: Failed to clear Elasticsearch index: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f9ff05269b0>: Failed to establish a new connection: [Errno -2] Name or service not known) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f9ff05269b0>: Failed to establish a new connection: [Errno -2] Name or service not known)
	```

	Helpful Commands:
	- tail log: `journalctl --unit=gunicorn -f`
	- see log: `journalctl --unit=gunicorn | tail -n 300`

	@taoteg was made aware of this on 2021-09-01. Seems like an ES issue. Must be fixed, but it does not block this PR, nor is it caused by this PR.
	
	This issues is likely caused by #189.

	</details>

</details>

### CODE REVIEW

**Comment by tacc-wbomar** [comment]
@taoteg I [added a commit](https://github.com/TACC/Core-CMS/pull/275#commits-pushed-d2ee161) relevant to testing this PR. Please pull. Sorry for the unexpected change.

<details>
<summary>Why the Change?</summary>

1. d2ee161 Merge from `main` to resolve any possible conflicts _before_ merging to `main`.
2. __e2d4fc0 When I Frankenstein-ed this PR out of a larger PR, I neglected some relevant content in `helpers.py`.__

</details>

**Comment by tacc-wbomar** [comment]
The submodule PR lost all its commits. I have blocked this PR. I will investigate the problem.

**Comment by tacc-wbomar** [comment]
✅ The submodule PR commits have been restored. This PR's description has been simplified.

**Review by duckonomy — APPROVED** [review]
Looks great 💯 

I had one suggestion. Could you make it so that enabling the `Use the "Citations" fields` checkbox makes the Citation fields required?
If not, no worries!

**Comment by tacc-wbomar** [comment]
> I had one suggestion. Could you make it so that enabling the `Use the "Citations" fields` checkbox makes the Citation fields required?

That sounds familiar, like something I also wanted. I'll look at options.

**Comment by tacc-wbomar** [comment]
@duckonomy How does dependency https://github.com/TACC/Core-CMS-Resources/pull/61 code look?

**Comment by tacc-wbomar** [comment]
@duckonomy I can "make it so that enabling the Use the 'Citations' fields checkbox makes the Citation fields required". I have created a ticket and provided direction, but I am compelled to merge without it.

- https://github.com/TACC/Core-CMS/issues/373

<details><summary>Why Merge Without This?</summary>

1. **Urgency to Merge**: Texascale 2021 is next month, so I need this code in now to prevent old way from being used. (The PR has been open since mid July.)
2. **Feature is Usable**: If user does not see Citations, then they can look back at the options chosen. But, reason 1 is the real reason I skip this.

But, this feature **will** be _very_ useful, so I anticipate coming back to it when it next applies to a new TACC plugin. It definitely improves UX.

</details>

**Pull request merged**
